### ISSUE TITLE
XDR Write Error: [object Object] is not a ScVal

### ISSUE THREAD

**Issue by rust-master** [stellar/js-soroban-client#124]
I'm using the Typescript client and facing an issue on React side when invoking the write function of the contract. 

Error:
```
caught (in promise) TypeError: XDR Write Error: [object Object] is not a ScVal
    at Function.value (soroban-client.min.js:2:1)
    at r.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at r.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at Function.value (soroban-client.min.js:2:1)
    at r.value (soroban-client.min.js:2:1)
```

Code Snippet:
```
import * as SorobanClient from "soroban-client";
import * as exampleProject from "ExampleProject"; // Typescript client

await exampleProject.invoke({
        method: "set_name",
        args: [
          SorobanClient.xdr.ScVal.scvString("Rust")
        ],
        fee: 100000,
      });

```

Contract Function:
```
 pub fn set_name(env: Env, value: String) {
        env.storage().instance().set(&NAME, &value);
    }
```

**Comment by AkhtarAmir** [comment]
The same error "[object Object] is not a ScVal" affecting us too even though the values are being converted perfectly to ScVal.

**Comment by AkhtarAmir** [comment]
Hey @rust-master, even after update I am still facing the same error can you provide a snippet how to pass the values now for avoiding this or is there anything else that needs to be changed?
